import { supabase } from './supabase';

const DEFAULT_TEMPLATES = [
  {
    name: "Office",
    description: "Synergy, bandwidth, and other ways to waste your afternoon",
    items: [" Circle back", " Touch base", "\"Take this offline\"", "\"Align\"", "\"Low-hanging fruit\"", "\"Big picture\"", "\"Move the needle\"", "\"Deep dive\"", "\"Holistic approach\"", "\"Best practices\"", "\"Synergy\"", "\"Value-add\"", "\"Game changer\"", "\"Scalability\"", "\"Ecosystem\"", "Meeting about another meeting", "\"Can everyone see my screen?\"", "Someone joins a meeting late and asks to recap", "Meeting with no clear outcome", "Action items with no owner", "Sends a meeting invite without checking availability", "\"Just flagging this\"", "\"Per my last email\"", "\"Friendly reminder\"", "\"I'll let you take this\"", "\"Not sure if this was intentional\"", "\"Happy to discuss\" (but clearly not)", "\"Let's table this for now\"", "Long chat messages instead of emails", "Someone entering a wrong meeting room", "Meeting that should have been an email", "Someone sharing the wrong screen", "\"You're on mute\"", "Echo / feedback chaos in an online meeting", "\"Let me stop sharing real quick\"", "Instantly following an email with a call", "Reply-all disaster", "CC'ing leadership as a threat", "\"At the end of the day…\"", "Urgent but not important tasks", "Acronym no one explains", "CCs random executives", "CCs way too many people", "Copies the entire email chain", "Escalates without warning", "Emails at night, expects results in the morning", "Wants instant replies", "Follows up after 5 minutes of asking for something", "Same issue, same person, multiple messages", "Sends \"???\" as a follow-up", "\"Are you there?\"", "Calls while you're responding by email", "Meeting gets rescheduled for the millionth time"],
    is_custom: false,
  },
  {
    name: "Customer Service",
    description: "Yes… we have answers. No… you won't like them",
    items: ["\"I've been a customer for YEARS\"", "\"I just have a quick question\"", "\"This will only take a second\"", "\"I spoke to someone earlier\" (no name, no details)", "\"No one told me that\"", "\"That doesn't make sense\"", "\"Can you make an exception?\"", "\"It worked last time\"", "\"I'm not trying to be difficult, but…\"", "\"This is unacceptable\"", "Pretends not to have seen the information", "Asks a question already answered", "Repeats the same question again, and again", "Talks over the explanation", "Hears only what they want", "\"So what you're saying is…\" (completely wrong)", "Wants it done yesterday", "Expects instant results", "Assumes magic is involved", "Wants a refund and to keep the product", "Tries to get free stuff \"for the inconvenience\"", "Thinks rules don't apply to them", "Shocked by standard policies", "Surprised by prices", "Surprised by wait times", "\"It's not working\" (no details)", "Ignored warnings", "Overly dramatic sighs", "Passive-aggressive politeness", "Talking very slowly (for no reason)", "Talking very loudly (for no reason)", "Long rant before the actual issue", "Apologizes while being rude", "Asks for a manager immediately", "Threatens to leave forever", "Mentions bad reviews", "\"I'll take my business elsewhere\"", "Name-drops managers", "Escalates without warning", "\"I know my rights\"", "Calls/comes right before closing", "Wants policy changed for them", "\"No one ever told me\"", "Wants you to break rules for them", "Thinks yelling helps", "Thinks persistence = success", "Tells their life story", "Overshares personal drama", "Blames spouse/kids/dog", "\"Sorry, I'm just frustrated\"", "Issue resolved but still unhappy", "Says \"never mind\" after 20 minutes", "Disappears mid-conversation", "\"Actually, one more thing…\"", "\"I know the owner\"", "\"I'm in a hurry\"", "Snaps fingers / waves aggressively", "Ignores greeting, immediately complains", "\"Your website said…\" (when it didn't)", "Refuses to read signs or instructions", "Brings up a completely unrelated problem", "Blames you for company policy", "\"I want to speak to the manager\"", "Claims \"everyone else\" does it for them", "Uses sarcasm instead of explaining the issue", "Says \"no offense\" right before offending you", "Demands help while refusing to provide info", "Compares you to another business negatively", "\"I'm paying your salary\""],
    is_custom: false,
  },
  {
    name: "Kids",
    description: "Tiny humans, giant chaos, zero chill",
    items: ["Random \"I love you\"", "Gives surprise hug", "Wants to hold your hand", "Says something accidentally profound", "Tries to help (but makes it worse)", "Compliments you sincerely", "Laughs uncontrollably at nothing", "Says goodnight to inanimate objects", "Makes you a \"gift\"", "Proudly shows terrible artwork", "Wants the same story / video / game again", "Says something wildly inappropriate in public", "Needs help with something they can do", "Insists \"I can do it myself\"", "Takes forever to do anything", "Needs one more thing before bed", "Asks \"why?\" repeatedly", "Refuses food they asked for", "Melts down over nothing", "Changes their mind instantly", "Ignores you when called", "Says something wildly incorrect with confidence", "Makes up their own rules", "Argues about obvious facts", "Thinks tomorrow is \"a long time\"", "Thinks five minutes is forever", "Connects unrelated events", "Asks impossible questions", "\"Watch this!\"", "\"I'm bored\"", "\"That's not fair\"", "\"I didn't do it\"", "\"It was an accident\"", "\"But I need it\"", "\"I'm not tired\"", "\"Just one more\"", "\"You promised\" (you didn't)", "Brutally honest observations", "Comments on strangers' appearance", "Asks loud personal questions in public", "Repeats something embarrassing you said", "Tells family secrets", "Mispronounces words adorably", "Makes up new words", "Swears accidentally", "Sticky hands out of nowhere", "Mysterious stains", "Pockets full of rocks", "Clothes inside out", "From laughing to crying in milliseconds", "World-ending sadness", "Over-the-top excitement", "Deep empathy out of nowhere", "Overreacts to minor inconvenience", "Forgets why they're upset", "Talks to themselves", "Talks to toys seriously", "Pretends to be an animal", "Makes random sound effects", "Sings nonsense songs", "Repeats the same joke multiple times a day", "Chooses chaos in quiet moments", "Sleeps in the weirdest position", "Asks a deep life question at bed time", "Insists they're not tired (while melting down)", "Renames a common object for no reason", "Suddenly hates the food they loved yesterday", "Meltdowns for random things", "Narrates everything they're doing", "Whispers loudly", "Refuses help, then gets mad when it's hard", "Claims they didn't do what you saw them do", "Dramatically pretends to be injured", "Invents an imaginary rule and enforces it", "Gets emotionally attached to a random object"],
    is_custom: false,
  },
  {
    name: "Spouses & Hearts",
    description: "Heart eyes, warm hugs, and everyday magic",
    items: ["Brings you a drink without being asked", "Listens when you vent", "Remembers how you take your coffee", "Saves you the last bite", "Does a chore you were dreading", "Holds your hand in public", "Laughs at your bad jokes", "Makes your favorite meal \"just because\"", "Checks if you got home safe", "Fixes something before you notice it's broken", "Leaves a sweet note (or text) randomly", "Lets you talk without trying to fix it", "Knows when you need space vs. a hug", "Notices small changes (haircut, mood, outfit)", "Brings you a snack they know you like", "Takes care of something you forgot", "Plans something small but thoughtful", "Puts their phone down when you're talking", "Does the annoying errand so you don't have to", "Says \"I'm proud of you\"", "Gives a long, quiet hug", "Listens to a same story again because it matters to you", "Notices when you're overwhelmed and steps in", "Keeps your favorite treat stocked", "Asks for your opinion and actually listens", "Gives a gentle forehead kiss", "Notices when you're tired and picks up the slack", "Lets you vent without minimizing your feelings", "Handles the awkward or annoying conversation", "Encourages you before something important", "Reaches for you in their sleep", "Takes pictures of you when you're not looking", "Thanks you for things you do all the time", "Says \"we'll figure it out together\"", "Notices your mood before you say a word", "Makes sure you eat when you're busy", "Keeps quiet when you're resting", "Remembers names and stories about your people", "Holds your face when they kiss you"],
    is_custom: false,
  },
  {
    name: "Spouses & Headaches",
    description: "Little habits, strong eye-rolls, deep sighs",
    items: ["Says \"huh?\" instead of listening", "Half-listening while on their phone", "Responds without hearing the question", "\"We already talked about this\"", "Says \"we need to talk\" with zero context", "Asks \"what's wrong?\" repeatedly", "Interrupts mid-sentence", "Finishes your sentences (wrongly)", "\"Relax\"", "\"Calm down\"", "Leaves dishes next to the sink", "Loads dishwasher incorrectly", "Leaves cabinet doors open", "Leaves drawers open", "Puts things almost away", "Creates clutter hot spots", "Notices mess but ignores it", "Leaves clothes on the floor", "Clothes next to the hamper", "Re-wears questionable clothing", "Mixes clean and dirty clothes", "Takes forever to get ready when you're already late", "Says \"I'm listening\" while on their phone", "Replaces things… but not where they belong", "Doesn't check their pockets", "Claims something is \"still clean\"", "Says \"five minutes\" (it's never five)", "Waits until the last minute", "Breathes a little too loudly", "Says \"it's fine\" when it is clearly not", "\"Did you see my text?\" (sent 30 seconds ago)", "Repeats a story you've heard 12 times", "Asks questions during a show you're watching", "Leaves phone volume on too loud", "Watches videos without headphones", "Scrolls phone during conversations", "Takes calls on speaker", "Asks you to fix things they're capable of fixing", "Leaves food containers open", "Takes the last bite without asking", "Says \"we\" when they mean \"you\"", "Can't decide what to eat", "Says \"I don't care\" (but does)", "Eats your snacks", "Forgets groceries you asked for", "Leaves crumbs everywhere", "Uses too many dishes", "Hogging the blankets", "Stealing pillows", "Walks too slowly or too fast", "Sleeps diagonally", "\"I don't care, you pick\" (then has opinions)", "Chews louder than necessary", "Leaves lights on in empty rooms", "Hits snooze repeatedly", "Turns lights off aggressively", "Changes the thermostat secretly", "Selective hearing", "Overthinks minor things", "Refuses to ask for help", "Asks for help immediately", "Overexplains simple things", "Uses your stuff and doesn't mention it", "Tells stories too slowly", "Tells stories too fast", "Corrects you unnecessarily", "Says \"I was just joking\"", "Gets defensive too quickly", "Avoids a difficult conversation", "Forgets to replace empty things", "Leaves one square of toilet paper", "Hums or sings loudly", "Leaves things where they \"make sense\"", "Starts a project and quickly abandons it…again", "Has strong opinions about nothing", "Has no opinion about important things", "Scrolls endlessly instead of getting up", "Misses obvious things", "\"You know what I mean\"", "Says \"you always\" or \"you never\"", "Answers a question with a story"],
    is_custom: false,
  },
  {
    name: "Family Gatherings",
    description: "Chaos, cookies, & questions you didn't ask for",
    items: ["\"When are you getting married?\"", "\"Why are you still single?\"", "\"How's work?\" (with judgment)", "\"How's school?\" (with judgment)", "Endless weather talk", "Someone brings up politics \"by accident\"", "\"When are you having kids?\"", "\"Do you remember me?\" (You do not)", "\"You've changed\"", "Politely asks but doesn't listen", "Someone critiques the cooking", "Questions your portion size", "Brings a dish unannounced", "Critiques the seating arrangement", "Doesn't eat what's offered", "Kids on sugar high running everywhere", "Someone arrives very late, very loudly", "Someone leaves early and quietly", "Traffic excuses", "Parking issues", "Older relative offers unsolicited life advice", "Oversharing about travel struggles", "Awkward silence", "\"When I was your age…\"", "Boomer relatives disagree with tech", "Gen A/Z commentary", "Someone brings a surprise extra guest", "\"Back in my day…\"", "Reminisces excessively", "Confusion over who's related to who", "Older relative makes young ones explain apps", "Someone tells an embarrassing story", "Someone calls out childhood antics", "Inappropriate jokes surface", "Kids interrupt adults constantly", "Someone gets emotional unexpectedly", "Someone overshares", "Someone drinks too much", "Someone falls asleep mid-conversation", "Mispronounced names", "Awkward hugs", "Singing / chanting", "Playing old games, fighting about the rules", "Group photo chaos", "Family toast speeches", "Passing down heirlooms", "Complaining about past gatherings", "Cleaning while complaining about cleaning", "Someone rearranges furniture", "Someone spills something", "Someone \"helps\" and makes it worse", "Passive-aggressive comments disguised as jokes", "Compliments with a hidden jab", "Competitive relatives", "Debate erupts unexpectedly", "Minor disagreement gets dramatically escalated", "Emotional hugs", "Awkward silence after a risky joke", "Overly sentimental gifts", "Debate over where everyone should sit", "Relative gossips about all others", "Someone brings out old photos", "Hugs that last longer than expected", "Someone compares you to another relative", "Kids performing unplanned \"talent shows\"", "\"We should do this more often\"", "Adults reverting back to bickering teenagers", "Someone playing matchmaker"],
    is_custom: false,
  },
  {
    name: "Dating",
    description: "Swipes, ghosts, and confusion",
    items: ["No bio at all", "Only group photos in their profile", "Sunglasses in every photo", "One blurry photo", "Photo with an ex cropped out", "Gym selfie", "Shows up late to the date, no apology", "Travel photo overload", "Picture with a dog (not theirs)", "\"Love to travel\"", "\"Foodie\"", "\"Fluent in sarcasm\"", "\"Looking for my partner in crime\"", "\"Work hard, play hard\"", "\"No drama\"", "\"Good vibes only\"", "\"Just seeing what's out there\"", "Height listed very specifically", "\"Not on here much\"", "First message says only \"Hey\"", "Looks nothing like their photos", "Conversation fizzles quickly", "One-word replies", "Immediate trauma dump", "Takes hours to reply", "Replies instantly every time", "Overuses emojis", "Doesn't use emojis at all", "Asks something already in your profile", "Matches but never messages", "Messages but never meets", "Suddenly disappears (ghosting)", "Reappears weeks later", "Says \"Sorry, I'm bad at texting\"", "Unmatches randomly", "Wants to move off the app immediately", "Asks for socials right away", "Sends voice notes unexpectedly", "Sends memes as flirting", "Awkward greeting hug", "Awkward greeting wave", "Instant chemistry", "No chemistry at all", "Nervous laughter", "Overthinking what to order", "Talks too much", "Doesn't ask many questions", "Checks phone during date", "Mentions ex casually", "Job talk too early", "Family talk too early", "Therapy talk too early", "Future plans too early", "Avoids all personal topics", "Repeats the same stories", "Overshares", "Asks oddly specific questions", "Love bombs on date one", "\"I'm a nice guy/girl/person\"", "Complains about all exes", "Talks only about themselves", "\"Had a great time!\" then ghosts", "Rude to service staff", "Won't make eye contact", "Talks negatively about everything", "Badmouths the app constantly", "Clearly not over someone", "Too intense too fast", "Avoids answering basic questions", "\"So… how do we do this?\" (bill)", "\"Just ask\"", "\"Not here for hookups (but…)\"", "Sexual comment within 3 messages", "Suggests \"walking date\"", "Suggests coffee \"just to see\"", "Cancels last minute", "Reschedules multiple times", "Sends a message meant for someone else", "Great chat but never asks you out", "Says \"let's do this again\", then vanishes", "Wrong age in profile, weird excuse about it", "Compares you to their ex", "Uses a photo from 10 years ago", "\"What are you looking for?\"", "\"Let's go with the flow\"", "Mentions other dates", "\"I'm just focusing on myself\"", "\"I wasn't expecting to meet someone like you\""],
    is_custom: false,
  },
  {
    name: "Teenangsters",
    description: "Memes, moods, and words you do not understand",
    items: ["\"It's giving…\"", "Responds with \"I dunno\" to everything", "\"I'm dead\"", "\"Low-key / high-key\"", "Says \"fine\" but is clearly not fine", "Sleeps until noon like it's an Olympic sport", "\"Say less\"", "\"You wouldn't understand.\"", "Reminded five times, still forgets it", "\"Cringe\"", "Communicates in memes", "Uses screenshots as evidence", "Speaks in TikTok audio references", "Understands jokes you don't", "Uses words in ways you don't understand", "Nothing is ever that serious", "Acts personally attacked by basic requests", "\"What?\" immediately after you finish explaining", "Asks what's for dinner, hates the answer", "Attention span maxed out at 2 minutes", "Watches videos at 1.5x speed", "Multiple apps open constantly", "Replies hours later", "Leaves messages on read", "Voice notes instead of calls", "Refuses phone calls", "Wears/attends/watches things \"ironically\"", "Wears headphones everywhere", "Suddenly very into one niche", "Outfit planned around vibes", "Calls out actions as \"toxic\"", "\"That's valid\"", "Avoids eye contact at all cost", "Talks about influencers like they're royalty", "\"The vibes are off\"", "Eye-roll so powerful it could cause wind", "\"Everyone else's parents let them.\"", "Dramatic bedroom door closing", "Acts embarrassed by your existence", "Claims they \"just cleaned\" their room", "Plays music you can feel through the walls", "Says \"It's not a phase\" (it is)", "Reacts to mild inconvenience like it's a crisis", "Wants independence but not responsibility", "Randomly very sweet when you least expect it", "Needs help but refuses all suggestions", "Sighs like life has wronged them", "\"I was just about to do that\"", "Says \"bruh\" during serious conversations", "Can't find something directly in front of them", "Treats \"clean your room\" like a hate crime", "Dramatically flops onto furniture", "Requests rides with zero notice", "Uses sarcasm like a weapon", "\"Why are you yelling?\" (You are not)", "Texts from the next room", "Suddenly affectionate, they want something", "Says \"I hate this house\" then never leaves"],
    is_custom: false,
  },
  {
    name: "Self-care",
    description: "For the love of...me",
    items: ["Drink a full glass of water", "Step outside for fresh air", "Make your bed (or don't, on purpose)", "Stretch for two minutes", "Eat something with real nutrients", "Do few minutes of 4-4-4-4 breathing", "Open a window for fresh air", "Wear comfy clothes", "Tidy one small thing", "Take three deep breaths", "Journal one sentence", "Notice one good thing", "Sit in silence briefly", "Do one thing at a time", "Put your phone down", "Say no without explaining", "Cancel plans if you need to", "Speak kindly to yourself", "Listen to a comfort song", "Watch a familiar show", "Write a feelings note", "Do something just for you", "Eat without scrolling", "Look at the sky", "Enjoy a hot drink slowly", "Pet an animal", "Take a mindful walk", "\"I am doing my best\"", "\"Progress, not perfection\"", "\"It's okay to rest\"", "Unsubscribe from an annoying mailing list", "Delete one app notification", "Set a tiny goal, write it down, do it, cross it off", "\"I'm allowed to take space\"", "Wash your face", "Brush your hair gently", "Take vitamins", "Rest your eyes for 30 seconds", "Write one kind sentence to yourself", "Let yourself daydream", "Name one thing you're proud of", "Notice your inner critic, tell it to shut up", "Light a candle", "Smell something nice", "Sit in sunlight", "Wrap up in a blanket", "Take a warm shower", "Listen to rain sounds", "Turn off unnecessary notifications", "Close unused tabs", "Watch wholesome videos online", "(Free space - can be used as wildcard)"],
    is_custom: false,
  },
];

let seeded = false;

export async function seedDefaultTemplates() {
  if (seeded) {
    return;
  }

  try {
    const { data: existingTemplates, error } = await supabase
      .from('bingo_templates')
      .select('name')
      .eq('is_custom', false);

    if (error) {
      console.error('Error checking existing templates:', error);
      return;
    }

    const existingNames = new Set(existingTemplates?.map(t => t.name) || []);

    for (const template of DEFAULT_TEMPLATES) {
      if (!existingNames.has(template.name)) {
        const { error: insertError } = await supabase
          .from('bingo_templates')
          .insert(template);

        if (insertError) {
          console.error(`Error seeding template ${template.name}:`, insertError);
        } else {
          console.log(`Seeded template: ${template.name}`);
        }
      }
    }

    seeded = true;
  } catch (error) {
    console.error('Error seeding templates:', error);
  }
}
